// <auto-generated />
namespace SistemaCred9.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class StatusContrato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StatusContrato));
        
        string IMigrationMetadata.Id
        {
            get { return "202005181614140_StatusContrato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
